package automata_pojo_hibernate.hibernate;
// Generated 27-Mar-2020 11:11:50 by Hibernate Tools 5.4.3.Final

/**
 * RequestParameters generated by hbm2java
 */
@SuppressWarnings("serial")
public class RequestParameters implements java.io.Serializable {

	private RequestParametersId id;

	public RequestParameters() {
	}

	public RequestParameters(RequestParametersId id) {
		this.id = id;
	}

	public RequestParametersId getId() {
		return this.id;
	}

	public void setId(RequestParametersId id) {
		this.id = id;
	}

}
